version: '3.8'

services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:Kubernetes@1993@db:5432/devops_academy_development
      REDIS_URL: redis://redis:6379/1
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://192.168.10.10:3000/ || exit 1"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kubernetes@1993
      POSTGRES_DB: devops_academy_development
    ports:
      - "5432:5432"  # Expose port for potential direct connections
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  sidekiq:
    image: ruby:3.1.0
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
    healthcheck:
      test: ["CMD-SHELL", "bundle exec sidekiqctl status /tmp/pids/sidekiq.pid"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:
  redis_data:
