version: '3.8'

services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
    env_file:
      - .env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devops_academy_development

  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data

  sidekiq:
    image: ruby:3.1.0
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
